import Stats from "@/components/stats";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboard Overview",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div className="w-full h-full flex flex-col gap-4">
      <Stats />
    </div>
  );
}
