import BooksManager from "@/components/books-manager";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboard Overview",
  description: "Generated by create next app",
};

export default function Home() {
  return <BooksManager />;
}
